version: "2"
services: 
    php:
        build: 
            context: ./
            dockerfile: Dockerfile
        container_name: php-server
        restart: always
        ports:
            - 8080:80
        volumes: 
            - ./php:/var/www/html
volumes: 
    php: {}